-- Design artifact only: this reflects the currently existing reviews table contract
-- used by the app code. It is not a migration and should not be executed directly.
-- It documents the required runtime behavior and the constraints that must be
-- preserved in the live Supabase project.

-- Actual current table contract (from the generated TypeScript schema):
-- public.reviews
--   id: uuid
--   booking_id: uuid not null
--   comment: text nullable
--   created_at: timestamptz not null
--   customer_id: uuid not null
--   moderated_at: timestamptz nullable
--   moderated_by: uuid nullable
--   moderation_reason: text nullable
--   moderation_status: text not null
--   occurrence_id: uuid nullable
--   rating: integer not null
--   worker_id: uuid not null
--
-- Relationship summary:
--   reviews.booking_id -> bookings.id
--   reviews.customer_id -> profiles.id
--   reviews.occurrence_id -> booking_schedule_occurrences.id
--   reviews.worker_id -> worker_profiles.id
--   reviews.moderated_by -> profiles.id
--
-- The app expects the existing column name to remain comment and does not use
-- review_text or updated_at on the live table.

/*
-- The live table should preserve these invariants:
-- 1. Each customer review belongs to the authenticated customer.
-- 2. Reviews are scoped to the booking and optionally to a specific occurrence.
-- 3. A completed booking can only be reviewed by its own customer.
-- 4. A recurring booking must use the actual completed occurrence worker, not a
--    client-supplied arbitrary worker_id.
-- 5. One review per booking/occurrence scope is required.
-- 6. Only completed bookings / completed occurrences are eligible.
-- 7. Moderation state and moderator metadata are retained for admin review.
--
-- The production DB must continue to enforce this with DB-side constraints and RLS:
--   - customer_id = auth.uid()
--   - booking.customer_id = auth.uid()
--   - booking.status = 'completed'
--   - occurrence.status = 'completed' for recurring bookings
--   - occurrence.worker_id = reviews.worker_id
--   - unique per booking when occurrence_id IS NULL
--   - unique per occurrence when occurrence_id IS NOT NULL
--   - selective customer read policies; no cross-customer review access
-- */

-- NOTE: this file intentionally avoids redefining the table in a way that would
-- conflict with the live schema. A future migration, if required, must be based
-- on the actual existing table contract and should not rename comment to
-- review_text or invent a new updated_at column without the production schema.
