
auth.token=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

defaults.org=tempstaff
defaults.project=react-native

defaults.url=https://sentry.io/
